### PR TITLE
Add support for Linux Mint 20.3 / 21 which is based on Ubuntu 20.04 / 22.04

### PR DESCRIPTION
**Pull request by Skywalker13**
Hello, see pull request title
Thank you
Regards

### CODE REVIEW

**Comment by ClundXIII** [comment]
Hello,

is this PR going to be merged any time soon? I would like to test this since I just finished migrating to my new Laptop.

**Comment by JoeJoeTV** [comment]
Would it be possible to add Linux Mint 21 and/or 21.1 additionally, since it's based on Ubuntu 22.04 and that's supported?

**Comment by Skywalker13** [comment]
I'm still using Mint 20... When I will upgrade my laptop, then I add Mint 21...

**Comment by Zomono** [comment]
Can someone please review and merge this PR?

**Comment by Skywalker13** [comment]
Linux Mint 21.1 is officially supported since 2.8.12; I close this merge request and thank you to the tuxedo-tomte team.

**Pull request closed without merging**
